&reference.sdo.sdo-exception.getCause;
